ALTER TYPE "ClmPriority" ADD VALUE IF NOT EXISTS 'MEDIUM';
ALTER TYPE "ClmRequestStatus" ADD VALUE IF NOT EXISTS 'SHARED_WITH_PRODUCT';
ALTER TYPE "ClmRequestStatus" ADD VALUE IF NOT EXISTS 'CLOSED';
